# Setup
title:            'Jeremy Wells'
tagline:          'Software Developer | Nashville, TN'
description:      >-
  Full-stack software engineer sharing favorite recipes
  in .NET, Angular, & anything else worth tinkering with.

url:              https://jeremywells.io
baseurl:          /

# Build settings
#theme: minima
plugins:
  - jekyll-feed

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

social-icons:
  - name: fab fa-github
    url: https://github.com/jsheridanwells
  - name: fab fa-dev
    url : https://dev.to/jsheridanwells
  - name: fab fa-twitter
    url: https://twitter.com/jsheridanwells
  - name: fab fa-linkedin
    url: https://linkedin.com/in/jsheridanwells

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
