# Setup
title:            'Jeremy Wells'
tagline:          'Software Developer | Nashville, TN'
description:      >-
  Full-stack software engineer sharing favorite recipes
  in .NET, Angular, & anything else worth tinkering with.

url:              jeremywells.io
baseurl:          /
author:           'Jeremy Wells'
twitter:
  username: jsheridanwells
  card: summary
social:
  name: Jeremy Wells
  links:
    - https://github.com/jsheridanwells
    - https://dev.to/jsheridanwells
    - https://twitter.com/jsheridanwells
    - https://linkedin.com/in/jsheridanwells
lang: en_US


# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

social-icons:
  - name: fab fa-github
    url: https://github.com/jsheridanwells
  - name: fab fa-dev
    url : https://dev.to/jsheridanwells
  - name: fab fa-twitter
    url: https://twitter.com/jsheridanwells
  - name: fab fa-linkedin
    url: https://linkedin.com/in/jsheridanwells

exclude:
  - _devto_versions/
